- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Enable UFW
  ufw:
    state: enabled

- name: Allow SSH and HTTP from anywhere
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80

- name: Allow port 9000 from internal device only
  ufw:
    rule: allow
    proto: tcp
    port: 9000
    from_ip: 10.200.16.100/29

- name: Deny all remaining incoming by default
  ufw:
    default: deny
    direction: incoming